[tool.commitizen]
name = "cz_conventional_commits"
version = "0.80.0"
tag_format = "v$version"
version_scheme = "semver2"
major_version_zero = true
#bump_pattern = "^(feat|fix|refactor|perf|ci|chore)(!)?:"
bump_pattern = "^(feat|fix|refactor|perf|ci|chore)(\\(.+\\))?(!)?:"

[tool.commitizen.bump_map]
"BREAKING CHANGE" = "MAJOR"
"feat" = "MINOR"
"fix" = "PATCH"
"refactor" = "PATCH"
"perf" = "PATCH"
"ci" = "PATCH"
"chore" = "PATCH"
