[tool.commitizen]
name = "cz_customize"
version = "0.80.0"
tag_format = "v$version"
version_scheme = "semver2"
major_version_zero = true

[tool.commitizen.customize]
schema_pattern = "^(feat|fix|refactor|perf|ci|chore)(\\(.+\\))?(!)?:(\\s.*)"
bump_pattern = "^(feat|fix|refactor|perf|ci|chore)(\\(.+\\))?(!)?:"
bump_map = {"BREAKING CHANGE" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "refactor" = "PATCH", "perf" = "PATCH", "ci" = "PATCH", "chore" = "PATCH"}
